### ISSUE TITLE
Home: Create section for Tetimonials

### ISSUE THREAD

**Issue by sub1120** [Vision-Clara/micindia#17]
Here we will show following details of founders in home page,

- Profile Pic
- Name 
- Designation
- Thought

### Tasks
- [x] Create component UI.
- [ ] Create a new collection `founders` in Database.
- [ ] Create an API end point to insert/update founder data into DB.
- [ ] Create an API end point to fetch founder data from DB.
- [ ] Connect UI with API end point
