### ISSUE TITLE
Home: Redesign micnews section

### ISSUE THREAD

**Issue by sub1120** [Vision-Clara/micindia#7]
Remove following unnecessary details from news and make it short and simple,

 - posters
 - thoughts
 - date and time.

### Tasks
- [x] micindia-webapp/micindia#19 
- [ ] Restyle component UI.
- [x] Create a new collection `micnews` in Database.
- [ ] Create an API end point to insert/update news data into DB.
- [x] Create an API end point to fetch news data from DB.
- [x] Connect UI with API end point
